Id: UniversityOfWashington.Foldit
Version: 20180312-1714f56737-win_x86
Name: Foldit
Publisher: University of Washington
License: Copyright (c) University of Washington
LicenseUrl: https://fold.it/portal/legal
Tags: proteins, folding
Description: Foldit is a revolutionary new game, in which you play to solve puzzles, and we test your solutions to work on curing cancer, AIDS, and a host of diseases.
Homepage: https://fold.it/
Installers:
  - Arch: x86
    Url: http://fold.it/portal/files/app/Foldit-win_x86.exe
    Sha256: f92e30c8dc0c1c7502940206d095172fba9676104a16693595266835cd798456
    InstallerType: nullsoft
